### ISSUE TITLE
게임 기능 TODO

### ISSUE THREAD

**Issue by minjune8506** [42-TRANSENDENCE/backend#73]
TODO
- [x] 코드 리팩토링 (기존 Game 코드)
- [x] 게임 초대
- [x] 게임 관전
- [x] socket 연결시 Authorization
- [x] Match History 저장
- [x] Match Making System
- [x] 게임과 관련된 업적 달성 검사
- [x] Special Game Mode
- [ ] 소켓 연결 버그 수정
